blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/awais-2005/video-downloader-web/discussions/new?category=ideas
    about: Suggest an idea for this project
  - name: Question
    url: https://github.com/awais-2005/video-downloader-web/discussions/new?category=q-a
    about: Ask a question about this project
